### ISSUE TITLE
Remove chart sub-title

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#114]
How can I hide the subtitle that comes up when I create a chart? 

![graph screenshot](https://cloud.githubusercontent.com/assets/21313941/21683944/ea5233d2-d35b-11e6-89bb-9f2606257fd2.jpg)

**Comment by abyot** [comment]
Normally, you can override / hide chart title by going to options and playing around with those under **General**

coming to the example graph you sent... not sure how you wanted to interpret the graph. 

The thing you canceled out is not a title rather data.

**Comment by abyot** [comment]
Yes, the questions themselves because you wanted to draw graph based on those questions.

What you are trying to do is like giving the metadata yet another name. Sorry, that is not possible.

In the visualizer, we have only two dimensions and a filter. We are drawing on a paper and have only two axis ... but the example graph contains the support levels; country; year; questions.
