### ISSUE TITLE
New questions on visualizations

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#13]
Hi Abyot,
- [ ] Could you please create graphs visible in the system homepage (the first page you access once logged in)  for **all** the data already inserted in the survey? Meaning, each question and sub-question should have their answers represented in a graph. In this way we will able to understand how the graphs will really look once our users will complete the survey. Thanks.

_Can we plan for a call - then I can explain some of these things._
- [ ] Could you please explain how we access country specific data from the aggregated data dashboards visible on the homepage? It would be good to have, for each answer, a dashboard with aggregated data and a **separate** one with data coming from each country.

_Can we plan for a call - then I can explain some of these things._
- [x] How can we make some graphs on the homepage public (e.g. graphs with aggregated data) and others visible only to selected users (e.g. graphs with country specific data)?

_This is managed through sharing - i.e. one can share graphs with other group of users. Each visualization output - whether chart, table or map - has a sharing setting through its favorite menu. To manage sharing, first we need to define our user groups.

We have more information about sharing in our user documentation. https://dhis2.github.io/dhis2-docs/master/en/end-user/html/dhis2_end_user_manual_full.html

See the sharing section of the different outputs._
- [x] We talked about a public dashboard page to be accessible from the outside. How will it look? Will it be read-only?

_Yes, public dashboard is read only. I am working on it and will share when it is ready._ 
- [ ] In the data entry green box, when selecting the year you want to insert data for, can you please leave only 2015 and delete the others? Data will refer only to that year anyway.

_The point with having multiple periods is that what if users want to enter/modify/view last or previous years data. By displaying only 2015, you are effectively blocking no access (through data entry module) to previous data. Is this what you want?_
- [x] Will you provide all our users with a user name and a password (to be changed later) when they first log into the system, or they will have to do it themselves? Do they have to create a profile the first time they log into the system? 

_This is an implementation issue. Anyone with "admin" user role can create as many users as needed. If you want me to create - then I need a list of your users. But, I would be happy if I could say away from implementation issues. Sure, I can advise and provide suggestions._
- [ ] We've seen that you inserted the "Country Report" button next to the green data entry box. It looks nice. but it's more like a list of the questions and answers rather than a real report. Could it come with graphs and dashboard as well (similar to the ones shown in the homepage) ? We can prepare a mock-up for you so that you can see how we want it.

_Have forwarded you and email, regarding a different discussion we had on this._

Thanks!

**Comment by chloedenavit** [comment]
Hi @abyot ,
Thanks for your replies. Would you mind replying in a new message instead of adding comments in italics to be sure that we receive notifications? Otherwise I'm afraid we might miss your replies. 

1. I see that you have created many new visualisations in the different outputs - thanks! What did you want to discuss on the call? Did you want us to make our own, or did you want to explain that some of the questions cannot be turned into graphs? 

2. This is surely easier to discuss on the phone, but just to rephrase: We want to have multiple Dashboards. One is global/aggregated, and the others are for every individual country. We don't want the country-specific visualisations to be on the same Dashboard as the aggregated results. Nicolas is hoping that we can click on a country name from a list, or a map, on the homepage, and then be taken directly to a Country-specific dashboard. 
I imagine this might not be possible, and if this is the case, maybe an alternate solution could be to have the full Dashboard (all visualisations) _only_  be viewable to the superuser, while the user entering data would not see any visualisations. After the user Completes all their data entry, the superuser would manually create visualisations for that country and "Share" it to a publicly viewable _country-specific_ Dashboard. Would this be possible? 
Any other idea of how we could make individual dashboards for every country-specific data?

3. Defining user groups:
We tried to define a user role for data entry, but there are so many authorities to choose from and it's quite difficult to figure out what they each are for.  I am wondering if you could create one user role for all Chairs (can enter data to any question for their country) and one user role for Focal Points (can enter data for only Output 5.4).  They would both only be able to see the 5 apps you mentioned on the last call.
I feel that it would be much faster for you to do it rather than us. Of course we can create each user profile, we just need your help on the Roles.

4. Years of data: There is no data from years previous to 2015 because the UN Network for SUN was created this year. Perhaps you can leave 2014 just to be safe but definitly the earlier years can be deleted.

Additional comments:
- [ ] In the visualisations/graphs that show Level of Support, is it possible to add a third column that says "N/A" for the number of countries that did not receive any type of support? I know that right now there are only three options for those questions (light, moderate, intense) but perhaps we could create a fourth option (N/A) that would be automatically populated if the user selects "No" for the previous question. 
The reason we want this is so that we can see the total number of countries (57) in every graph, to know how many have done that activity and how many have not done it (N/a). 

- In addition, I am wondering if it would be possible for data entry users to click on a link that would send them directly into the App for data entry, without passing through the home page of visualisations?  After they finish completing their data, they can then click on the logo at the top right to see the graphs, but when they first log on, we would prefer if they are sent directly to the data entry page. Is this possible?

Thanks!

**Comment by abyot** [comment]
Re: Adding "N/A" for level of support

Adding the 4th option is easy, it is just a matter of adding a new metadata "N/A". The bigger task, though, is auto-populating them. It is a little complicated.

Re: Data entry as start page

This is possible, but again your second questions makes it almost impossible. We have an option to configure a start or home page. There are multiple ways to access this page - the first time you login, or once you have logged in and browsing different apps, if you want to go back to home page, you can do that by clicking the logo at the top left.

So, you have to decide - if one is made a home page, all others need to be searched.

If you have different user groups - those working on data entry and others in visualization - you can assign their start page accordingly.

**Comment by chloedenavit** [comment]
@Alisia1  can we close this issue? We can open new ones when we get feedback from the pilot and need Abyot to make more edits to the Dashboard, I think.

**Comment by Alisia1** [comment]
yes I will close it!
