### ISSUE TITLE
Sub-questions not appearing in French version

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-inventory#132]
Hi @abyot,
In question 5.1.2., when I am in English, the following sub-questions appear.

For Yes:
![image](https://cloud.githubusercontent.com/assets/21313941/22373046/516b6160-e4a0-11e6-94f8-e2856c76d111.png)

For No:
![image](https://cloud.githubusercontent.com/assets/21313941/22373055/5a87397c-e4a0-11e6-8383-82a8f90d8be8.png)

But when I change to French, the sub-questions never appear, whether I choose Yes or I choose No (You can see that I cannot scroll down any further):

![image](https://cloud.githubusercontent.com/assets/21313941/22373182/f17b1970-e4a0-11e6-8d62-de38238c10f5.png)

Any idea how I can fix this?

**Comment by abyot** [comment]
Oh ya, great that you raised it ... at some point was thinking of writing you but then forgot it...

This is related to the translation of the values... technically it would be much much easier if we do not translate the drop down answers.

For example we have used "Yes" as skip logic value... and this was used in the system... but now because of the translation ... it is "Oui" so there is a mismatch. I think you raised this in one of this issues and I have used in code if "Yes" or "Oui" ... and I remember this addressing the issue... but then now you are saying it is coming back. Can you make sure this is not a cache issue and also we have "Oui" with no trailing spaces? I will also check from my side one more time.

As to the "No", this will not work... and this was the thing I wanted to ask you. Do we have a skip logic value other than "Yes" that triggers for the showing of a question? Now seems we have a "No". Do we have any other value? Numbers are ok - unless we have Arabic vs Roman numbers.

I am able to use both "Oui" and "Yes" for "Yes" because, the outcome of the  skip logic was always the same when a Yes value is used - we are always showing the question referred. Unfortunately, this is not the case for "No". It is only in place - question 5.1.2 - that we are showing the question, otherwise we are always hiding. This makes it almost impossible with our current approach. We need to find a new way of handling skip logic - actually not sure what solution we can bring.

The issue here is not the system being not able to support different languages. It is just that we are stretching it a bit - we are trying to use the same system for multiple locale at the same time. This is a problem. Much more serious problem will happen if we try to use the system for multiple calendar at the same time. This is a total no no - even data entry will not be possible.

**Comment by chloedenavit** [comment]
Hi Abyot, Thanks for explaining. 

I think one solution could be to remove the sub-question that is triggered by "No" and make the other sub-question (for Yes) always show up (removing skip logic) and change the question so that we are asking people "If yes, please answer this question. If No, please answer this other question." 

However, what will we do when they choose N/A? Could we make the question NOT appear if the user selects N/A?

**Comment by abyot** [comment]
Our skip logic rule is simple --- we display a question whenever a value is matched. 

This means if "N/A" is not used in the rule - as skip logic value - then a question will not show up when users select "N/A".

**Comment by chloedenavit** [comment]
OK, so can you set a skip value to be both Yes and No ? Or do you think my suggestion wont work?

**Comment by abyot** [comment]
sorry, I did not understand "set a skip value to be both Yes and No"?

A question for you: Have you added / removed a question to/from Output 5.1? With the French translation I can't figure out what is what.

**Comment by abyot** [comment]
I have found the problem why the "Oui" was not working, it was related to priority ... I need your decision on this.

I am not if the screenshots below explain it well...

![image](https://cloud.githubusercontent.com/assets/4967749/22375713/81067120-e4ab-11e6-9757-638b2519c643.png)


![image](https://cloud.githubusercontent.com/assets/4967749/22375674/5dfb4eda-e4ab-11e6-8f52-07e16851dd2a.png)


The first one, which is used by the system currently, gives priority when there is an exact match between values users have entered and values defined in the rule. If there is a mismatch, then rule won't trigger. It failed to handle the issue you just reported because there is a mismatch between the rule and the value hence... the rule was not triggered... the system won't even check the Oui if/else statement because there is already a mismatch.

The second screenshot, gives priority to rules triggered when Yes is selected, it will also handle Oui. This means we are checking for exact matches for those questions whose skip logic value is other than "Yes".

I don't see an issue with new approach. A more robust solution is, of course, to be able to translate the values entered as skip logic value. It is a big task but doable.

**Comment by chloedenavit** [comment]
Hi Abyot, sorry I did not reply to this sooner!!
This approach (less robust) of the priority rules being triggered for both Yes and Oui would be perfect. Could you please make this change? 
Thanks!

**Comment by abyot** [comment]
This is fixed.
