### ISSUE TITLE
Upload link to a PDF doc in Output 5.4.4. and Output 5.4.5

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#36]
Hi Abyot,

- [ ] 
[UN Agencies Methodology for Nutrition Expenditure Tracking.pdf](https://github.com/abyot/sun-inventory/files/568751/UN.Agencies.Methodology.for.Nutrition.Expenditure.Tracking.pdf)
can you please create a link to the PDF here attached in the definition box of the Outputs 5.4.4 and Outputs 5.4.5? The link should be at the end of both definitions, meaning, at the end of the sentence "Please refer to the guidance note herewith attached for guidance on tracking financial allocations to nutrition."

thanks!

**Comment by abyot** [comment]
Hi @Alisia1 

Look at the screenshot below:

![image](https://cloud.githubusercontent.com/assets/4967749/19965706/9c1e1f7e-a1c8-11e6-925d-1ee7aac8cbc9.png)

I would be happy if we could follow the approach of 5.4.4 than 5.4.5. If you could change the definition's text to something like "... follow the link above for more guidance ..." or something like that, it will work nice.

My concern with the approach of 5.4.5 is that the solution is not as such stable. It depends on other modules. There is a high possibility that these items might change - because these items are not designed to store link. If this happens we will have a problem. 5.4.4 is a proper solution - we are using items that are made to store link.

Another question:

Where do you want to store the guidance? I remember at some point Nicolas mentioning about global document repository. What are the decisions on this?

**Comment by Alisia1** [comment]
Ok we can follow the approach of Output 5.4.4. So I guess we can't insert the link at the end of the definition?
If not, can we put it below the definition and not above?
thanks!

**Comment by abyot** [comment]
I have changed the position.

Please note that the link box is always visible, while the definition box is available only when a user has clicked on the question.
