### ISSUE TITLE
URGENT Pilot test Users Profile

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#37]
Hi Abyot!

So, as on Monday our pilot test will go live, I have created 3 users profile for the colleagues who will fill in the survey. They are:
**User name**: UN Network_Guatemala **Password**: Guatemala123
**User name**: UN Network_Sudan  **Password**: Sudan123
**User name**: UN Network_Kyrgyzstan  **Password**: Kyrgyzstan123
I have created those profiles by duplicating the dataentry one. However, when accessing the survey with one of the profiles above, if I try to start the survey I can only select Test Country 1 or Test Country 2 among the Organisation Units.

Can you please help me with this?

Thanks!

**Comment by abyot** [comment]
Yes, that is because the dataentry user did not have access to all the countries.

You can control which countries a user can access by going to 

Apps -> Maintenance - Users -> User -> Edit -> **Data capture and maintenance organisation units**

A user can capture data to those organisation unit selected in this section.

Also, never create a username containing a space char. "UN Network_Guatemala" is not good.

If you really want to be descriptive - you could say un_network_guatemala.

I would say guatemala is just enough. The system is any ways about UN Network .

**Comment by Alisia1** [comment]
Thanks, I will change the user name!

- [ ] can you please delete the Test Country 1 and Test Country 2? We don't want them to see that.
thanks!

**Comment by abyot** [comment]
It is our test countries where I use during development. If you do not want to see them, do not assign them to user. You can follow the steps in my earlier message.
