### ISSUE TITLE
Data saved turn into yellow

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#70]
Hey Abyot!
We've noticed that entered in the Inventory turn into yellow now and not in green as per the dashboard..
Is there any reason for that? Does it mean that data are not saved because the user has not clicked on "save" yet? I recall reading something referring to the yellow color into the DHIS2 manual but I am not sure..
Please let me know!
thanks
Alisia

**Comment by abyot** [comment]
Hi @Alisia1 

Yes that is a difference ... the yellowish color is to notify you data is not saved. To save data in inventory you need to click the save button. When clicking save, there will be a popup notifying whether data is saved or not.

In the dashboard, data was saved automatically that is why the green indicator comes. We are doing it differently here because that is how @chloedenavit wanted it.

**Comment by Alisia1** [comment]
thanks Abyot! I will specify that difference in the manual I am writign about the Inventory!
