### ISSUE TITLE
Survey marked as complete even when not complete

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#76]
- [ ] Kyrgyzstan survey was “marked as complete” even though they did not answer all questions (ex. 2.2.) – this should not be allowed.

**Comment by abyot** [comment]
@Alisia1 @chloedenavit 

The system doesn't allow to complete without answering all questions. The most likely scenario that happened is - they edited/removed value after completing the report.

Now I have made a change so that it is not possible to edit once a report is marked complete. Editing is possible once a report is marked not-complete.

![image](https://cloud.githubusercontent.com/assets/4967749/21102436/80ec21d6-c07e-11e6-8e25-4d0ad1ab2668.png)

**Comment by chloedenavit** [comment]
Thanks @abyot, this feature is great. Could you edit the sentence as below (the capitalization is just to show you where all the changes are, but all text should be not-capitalized):

Since the report WAS submitted as complete, editing is not possible. If editing is required, the report MUST be marked not-complete BY CLICKING ON THE RED BUTTON ABOVE.

**Comment by abyot** [comment]
:) sure will fix.

but we are kind of locking things here ... what if we wanted to change the color to something other than red or move the button to the right, left, bottom? Given the experience so far, I am sure we are going to do this at some point ...

do we have to be this explicit? we need to kind of trust the innovative capacity of users..

**Comment by chloedenavit** [comment]
@abyot , could you also set this "lock" for the Inventory, after they will mark as complete?
