### ISSUE TITLE
Hide the Inventory data from the Dashboard apps

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#95]
Hi Abyot,
I was trying to create a graph in the Dashboard, and I noticed that some elements of the Inventory (e.g. the answers categories) can be visible again..I remember that we hid them, when we did not have the actual Inventory yet.
![capture for abyot - inventory elements in the dashboard](https://cloud.githubusercontent.com/assets/22884743/21137456/e2fd5a4c-c129-11e6-906f-3a77190316f4.PNG)

- [ ] Can we hide them again? we would like to people using the Dashboard to be able to see only elements referring to the Dashboard, and people filling it the Inventory to see only the elements belonging to the Inventory. 

Once the two tools will be merged into the same system, will it be possible?
thanks

**Comment by abyot** [comment]
Hi @Alisia1,

Sure, I can hide/remove them.... but the issue I think here is we have a not-so-clean metadata. Since we were adding/removing items in the process we are left with metdata which we are not using anymore.

**Comment by abyot** [comment]
Yes, those extra questions. There are also associated dimensions that we created for them...

... actually deleting them for me will be a little tricky since I don't know the questions / contexts.

What I can do is identify all the question that are not assigned to any of the outputs / outcomes and also "UN Network for SUN Annual Reporting"... and delete them. Is this ok for you or you want to filter / keep some of them?

**Comment by chloedenavit** [comment]
Yes, I think any question that isn't assigned to any output or to that data set can safely be deleted. Thank you!

**Comment by abyot** [comment]
ok, I will remove them.

For now, I have removed some of the dimensions that came from the inventory.

Still, something I couldn't understand, what will you do when the inventory and dashboard are combined again?

**Comment by chloedenavit** [comment]
Our question is, can we hide Inventory elements from the Dashboard users, and hide Dashboard elements from the Inventory users? I understand that the Admin will see all of them mixed together, and that is okay, but I am wondering about data entry users.

**Comment by abyot** [comment]
Yes, that is possible.

However, I would like you ( @Alisia1 and Nicolas ) to first come up with an implementation strategy ... for example who are your users? Will they access the same system? From the same country? Totally different group of users?

What I see at the moment is the need to just hide... would be nice to look at the implication.

**Comment by Alisia1** [comment]
Hi Abyot,
please let me talk to Nicolas about it, I will come back to you as soon as possible!
Thanks

**Comment by chloedenavit** [comment]
Hi Abyot,
Alisia's now off contract and Nicolas is on leave for the holidays until Jan 3. However I think I can answer this question for you. 

The users will be totally different:
- In the Inventory, each agency in each country will have one  person who will fill the data for their agency (This equates to about 5 usernames per country = one for each agency). 
- In the Dashboard, there will be one username for the whole country, because one person will gather all agencies' responses and enter data for that country (we did this in the pilot and it worked).
 
Therefore, each username can be associated with either one OR the other tool, but it is not necessary to give one user access to both tools. 
This is because the Dashboard username is for the whole country team, whereas in the Inventory, we want to be able to know exactly which agency entered data. 

If one person is in charge of completing data for both tools, we can give them 2 usernames: one username for the Dashboard (with the name of the country, ex: Sudan) and one username for the Inventory, which will need to include their agency (ex: Sudan-UNICEF).

Only the superuser will be able to see both tools and both metadata.

Does this make sense?

**Comment by chloedenavit** [comment]
Abyot will refer me to the documentation instructions.

**Comment by abyot** [comment]
Here is some info 

- managing users, user groups and user profiles
https://ci.dhis2.org/docs/master/en/user/html/dhis2_user_manual_en_full.html#mgt_user_role_group

- managing sharing settings of meta data objects
https://ci.dhis2.org/docs/master/en/user/html/dhis2_user_manual_en_full.html#d1245e5554
